### ISSUE TITLE
how to support old CanonicalizationMethod ?

### ISSUE THREAD

**Issue by chenghonour** [moov-io/signedxml#14]
For some reasons, the following algorithm must be used in the project
http://www.w3.org/TR/2001/REC-xml-c14n-20010315

**Comment by CamiloHernandez** [comment]
I ran into the same problem. The version you're trying to use is 1.0 which is now outdated. The new 1.1 version is backward compatible and is supported by this library. Swap the URL for the new one (https://www.w3.org/TR/xml-c14n/) and sign the document, everything should work fine.

In some cases, you will need to change the URL back again to the old one (http://www.w3.org/TR/2001/REC-xml-c14n-20010315) after signing for schema compatibility.

**Comment by chenghonour** [comment]
@CamiloHernandez but https://www.w3.org/TR/xml-c14n/ is not in the support list..it run out a unsupported error

**Comment by CamiloHernandez** [comment]
Whops, sorry. Misread the question. 

Ok, so you are trying to use plain Canonicalization but as far as I can see this library only supports Exclusive Canonicalization, which means that it "excludes ancestor context from a canonicalized subdocument". Generally speaking, that should not be a problem unless you need the ancestor context in your signature, otherwise, in its current state, this library will not work for you.

If excluding ancestor context is not a problem for you, then the general idea of my last answer still holds. You can swap the 1.0 URL with the new 1.1 one and it should work. The link for 1.1 ExclusiveCanonicalization is: http://www.w3.org/2001/10/xml-exc-c14n#

Do keep in mind that this is a workaround, as this algorithm you're trying to use not technically supported.

**Comment by chenghonour** [comment]
@CamiloHernandez Okay, i will try it .  Thank you for your patient explanation.

**Comment by chenghonour** [comment]
@CamiloHernandez ohh, so hard.Because to connect to the old institutional system, I must use this expired algorithm.  Otherwise, the signature will be inconsistent.  Do you have a recommended tool library to support http://www.w3.org/TR/2001/REC-xml-c14n-20010315 ?

**Comment by adamdecaf** [comment]
It looks like this is [supported on a fork of signedxml](https://github.com/ma314smith/signedxml/compare/master...daugminas:signedxml:master) so would cherry-picking that onto master be accepted? I need this REC- algorithm as well.

**Comment by adamdecaf** [comment]
We support C14N10Rec now. Can you try out the v1.0.0 release and let us know how it works?
